### ISSUE TITLE
sorry for bothering, could you please tell me how you organize .spacemacs configuration?

### ISSUE THREAD

**Issue by ChenXiyu** [trishume/dotfiles#1]
hello, I want to organize my dotfiles with git repo like you did, and i faced a problem:
i tried to using symbol link and hard links to link `dotfile_repo/spacemacs` to `$HOME/.spacemacs`, 
- but seems git change files in each version control operation(inode  number changes), so the hard link don't much works at this circumstances, 
- and seems like emacs(using spacemacs) did not follow the symbol links. when i link `$HOME/.spacemacs` as a symbol link and lunch emacs, spacemacs try to create a new `$HOME/.spacemacs`.
Putting `(setq vc-follow-symbol-link t)'  at the head of `.emacs.d/init.el` still not working for me.

I notice that your spacemacs configuration at this repo looks like a symbol link, so, could you please tell me how you done with this?

**Comment by trishume** [comment]
I'm not sure exactly, it's been a while since I used spacemacs. I just run `rake` in my dotfiles directory and that automatically sets up the symlinks.

I really don't recommend you use my dotfiles directly though, if you want to use my spacemacs settings, it's probably better to just copy and paste what you want.

**Comment by ChenXiyu** [comment]
Thank you for your reply.
Yes, I have my own spacemacs config, I just trying to figure out how to sync the `dotfiles` on repo and `$HOME/.spacemacs` automatically without file links.
I have read your rakefile. In my understanding, you are using symbol link to do that, your `$HOME/.spacemacs` should be a symbol link to your `dotfiles/emacs+/spcemacs.symblink` file. This is what I meant to do at the beginning, but it doesn't works for me.
Anyway, thank you for your time, i'll continue to figure out what's wrong with it.

**Comment by ChenXiyu** [comment]
My bad,
In installation script, I add a space at the absolute path of dotfile directory accidentally.
after i delete it, The symbol link works.
